version: "3"

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: skill_shuffle
      MARIADB_USER: mak7ilenin
      MARIADB_PASSWORD: darkeden333
    ports:
      - "3306:3306"
    volumes:
      - ./database/skill_shuffle.sql:/docker-entrypoint-initdb.d/skill_shuffle.sql

  server:
    image: server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  client:
    image: client
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server